language: node_js
node_js:
  - 14

services:
  - docker

# Pre-testing installs
install:
  - echo "nothing needs to be installed"

# Scripts to be run such as tests
before_script:
  - echo "no tests"
  
script:
  - docker --version # print the version for logging
  # Build
  - docker build -t udagram-api-feed ./udagram-api-feed
  - docker build -t udagram-api-user ./udagram-api-user
  - docker build -t udagram-frontend ./udagram-frontend
  - docker build -t reverseproxy ./udagram-reverseproxy
  # Tagging
  - docker tag udagram-api-feed chiennm99/udagram-api-feed:v16
  - docker tag udagram-api-user chiennm99/udagram-api-user:v16
  - docker tag udagram-frontend chiennm99/udagram-frontend:v16
  - docker tag reverseproxy chiennm99/reverseproxy:v16

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  # Push
  - docker push chiennm99/udagram-api-feed:v16
  - docker push chiennm99/udagram-api-user:v16
  - docker push chiennm99/udagram-frontend:v16
  - docker push chiennm99/reverseproxy:v16